#ifndef PAGE_INDEX_H
#define PAGE_INDEX_H

const char page_index[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>AirDoom</title>\n"
"<style>\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{background:#fff;color:#111;font-family:system-ui,sans-serif;font-size:14px;padding:12px}\n"
"h1{font-size:1.2rem;font-weight:700;border-bottom:2px solid #111;padding-bottom:6px;margin-bottom:14px}\n"
"h2{font-size:1rem;margin-bottom:10px}\n"
".card{border:1px solid #ccc;border-radius:6px;padding:14px;margin-bottom:12px}\n"
"label{display:block;font-size:0.8rem;color:#555;margin-bottom:4px;margin-top:10px}\n"
"label:first-child{margin-top:0}\n"
"input,select{width:100%;padding:8px;border:1px solid #bbb;border-radius:4px;font-size:14px;background:#fafafa}\n"
"input[readonly]{background:#f0f0f0;color:#555}\n"
"button{display:block;width:100%;padding:10px;margin-top:12px;background:#111;color:#fff;border:none;border-radius:4px;font-size:14px;font-weight:600;cursor:pointer}\n"
"button:active{background:#333}\n"
"button.sm{width:auto;padding:5px 12px;margin-top:0;font-size:12px;float:right}\n"
"table{width:100%;border-collapse:collapse;font-size:13px}\n"
"th{text-align:left;padding:7px 8px;background:#f0f0f0;border-bottom:2px solid #bbb;font-size:12px;color:#555}\n"
"td{padding:7px 8px;border-bottom:1px solid #eee}\n"
"tr:hover{background:#f7f7f7;cursor:pointer}\n"
"tr.sel{background:#e8e8e8;font-weight:600}\n"
".tbl-wrap{max-height:260px;overflow-y:auto;border:1px solid #ddd;border-radius:4px;margin-top:8px}\n"
".row{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}\n"
"#errors{background:#fff0f0;border:1px solid #f99;color:#c00;padding:10px;border-radius:4px;margin-bottom:10px;font-size:13px;display:none}\n"
".center{text-align:center;padding:30px}\n"
".spin{display:inline-block;width:32px;height:32px;border:3px solid #ddd;border-top-color:#111;border-radius:50%;animation:sp 0.8s linear infinite}\n"
"@keyframes sp{to{transform:rotate(360deg)}}\n"
"pre{background:#f5f5f5;border:1px solid #ddd;border-radius:4px;padding:10px;font-size:11px;overflow-x:auto;white-space:pre-wrap;word-break:break-all}\n"
"a.dl-btn{display:inline-block;padding:8px 16px;background:#111;color:#fff;text-decoration:none;border-radius:4px;font-size:13px;margin-right:8px}\n"
"section{display:none}\n"
".vis{display:block!important}\n"
"@media(min-width:600px){.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}}\n"
"</style>\n"
"</head>\n"
"<body onload=\"getStatus()\">\n"
"<h1>&#128246; AirDoom</h1>\n"
"<div id=\"errors\"></div>\n"

"<section id=\"loading\" class=\"vis\">\n"
"<div class=\"card center\"><div class=\"spin\"></div><p style=\"margin-top:12px\">Connecting...</p></div>\n"
"</section>\n"

"<section id=\"ready\">\n"
"<div class=\"grid\">\n"
"<div class=\"card\">\n"
"<div class=\"row\"><h2>Nearby Networks</h2><button class=\"sm\" type=\"button\" onclick=\"refreshAps()\">&#8635; Scan</button></div>\n"
"<div class=\"tbl-wrap\"><table id=\"ap-list\"><tr><td style=\"color:#aaa\">Press Scan...</td></tr></table></div>\n"
"</div>\n"
"<div class=\"card\">\n"
"<h2>Attack Config</h2>\n"
"<label>Target</label>\n"
"<input type=\"text\" id=\"target_ssid\" placeholder=\"Select from list\" readonly required>\n"
"<label>Attack Type</label>\n"
"<select id=\"attack_type\" onchange=\"updateFields(this)\" required>\n"
"<option value=\"0\">Passive Sniffer</option>\n"
"<option value=\"1\">Handshake Capture</option>\n"
"<option value=\"2\" selected>PMKID Attack</option>\n"
"<option value=\"3\">Deauth DoS</option>\n"
"<option value=\"4\">Beacon Spam (Rickroll)</option>\n"
"<option value=\"5\">Mass Deauther (Nuke Mode)</option>\n"
"</select>\n"
"<div id=\"method_grp\" style=\"display:none\">\n"
"<label>Method</label>\n"
"<select id=\"attack_method\"></select>\n"
"</div>\n"
"<label>Timeout (s)</label>\n"
"<input type=\"number\" id=\"attack_timeout\" min=\"1\" max=\"255\" value=\"30\" required>\n"
"<button type=\"button\" onclick=\"runAttack()\">&#9654; Launch Attack</button>\n"
"</div>\n"
"</div>\n"
"</section>\n"

"<section id=\"running\">\n"
"<div class=\"card center\">\n"
"<div class=\"spin\"></div>\n"
"<p style=\"margin-top:12px;font-weight:600\">Attack Running...</p>\n"
"<p id=\"running-progress\" style=\"margin-top:6px;color:#555\">0/0s</p>\n"
"</div>\n"
"</section>\n"

"<section id=\"result\">\n"
"<div class=\"card\">\n"
"<div class=\"row\"><h2>Results</h2><button class=\"sm\" type=\"button\" onclick=\"resetAttack()\">&#10227; New</button></div>\n"
"<p id=\"result-meta\" style=\"font-size:13px;color:#555;margin-bottom:12px\"></p>\n"
"<div id=\"result-content\"></div>\n"
"</div>\n"
"</section>\n"

"<script>\n"
"var S={READY:0,RUNNING:1,FINISHED:2,TIMEOUT:3};\n"
"var T={PASSIVE:0,HANDSHAKE:1,PMKID:2,DOS:3};\n"
"var selId=-1,atkTimeout=0,elapsed=0,timer;\n"

"function getStatus(){\n"
"  var r=new XMLHttpRequest();\n"
"  r.onload=function(){\n"
"    var b=r.response; if(!b) return;\n"
"    var d=new Uint8Array(b);\n"
"    var state=d[0],type=d[1],sz=new Uint16Array(b,2,1)[0],cnt=new Uint8Array(b,4);\n"
"    hideAll();\n"
"    if(state===S.READY){show('ready');}\n"
"    else if(state===S.RUNNING){show('running');setTimeout(getStatus,1500);}\n"
"    else if(state===S.FINISHED){showResult('FINISHED',type,sz,cnt);}\n"
"    else if(state===S.TIMEOUT){showResult('TIMEOUT',type,sz,cnt);}\n"
"  };\n"
"  r.onerror=function(){showErr('Cannot reach device. Reconnect to Realdev AP.');setTimeout(getStatus,3000);};\n"
"  r.ontimeout=function(){setTimeout(getStatus,3000);};\n"
"  r.open('GET','status',true);\n"
"  r.responseType='arraybuffer';\n"
"  r.send();\n"
"}\n"

"function refreshAps(){\n"
"  var tbl=document.getElementById('ap-list');\n"
"  tbl.innerHTML='<tr><td colspan=\"3\" style=\"color:#aaa;text-align:center\">Scanning...</td></tr>';\n"
"  var r=new XMLHttpRequest();\n"
"  r.onload=function(){\n"
"    tbl.innerHTML='<tr><th>SSID</th><th>BSSID</th><th>RSSI</th></tr>';\n"
"    var b=r.response; if(!b) return;\n"
"    var d=new Uint8Array(b);\n"
"    for(var i=0;i<d.byteLength;i+=40){\n"
"      var ssid=new TextDecoder().decode(d.subarray(i,i+32)).replace(/\\0/g,'');\n"
"      var bssid=''; for(var j=0;j<6;j++) bssid+=d[i+33+j].toString(16).padStart(2,'0')+(j<5?':':'');\n"
"      var rssi=d[i+39]-255;\n"
"      var tr=document.createElement('tr');\n"
"      tr.innerHTML='<td>'+(ssid||'<i>Hidden</i>')+'</td><td style=\"font-family:monospace;font-size:11px\">'+bssid+'</td><td>'+rssi+'</td>';\n"
"      (function(id,s,row){row.onclick=function(){selectAp(id,s,row);};})(i/40,ssid,tr);\n"
"      tbl.appendChild(tr);\n"
"    }\n"
"  };\n"
"  r.onerror=function(){tbl.innerHTML='<tr><td>Scan failed</td></tr>';};\n"
"  r.open('GET','ap-list',true); r.responseType='arraybuffer'; r.send();\n"
"}\n"

"function selectAp(id,ssid,el){\n"
"  selId=id;\n"
"  document.getElementById('target_ssid').value=ssid||'Hidden';\n"
"  document.querySelectorAll('#ap-list tr').forEach(function(r){r.classList.remove('sel');});\n"
"  el.classList.add('sel');\n"
"}\n"

"function runAttack(){\n"
"  if(selId===-1){alert('Select a target first.');return;}\n"
"  var type=parseInt(document.getElementById('attack_type').value);\n"
"  var method=parseInt(document.getElementById('attack_method').value)||0;\n"
"  var tout=parseInt(document.getElementById('attack_timeout').value);\n"
"  var buf=new ArrayBuffer(4);\n"
"  var v=new Uint8Array(buf);\n"
"  v[0]=selId;v[1]=type;v[2]=method;v[3]=tout;\n"
"  var r=new XMLHttpRequest();\n"
"  r.open('POST','run-attack',true); r.send(buf);\n"
"  atkTimeout=tout; elapsed=0;\n"
"  hideAll(); show('running');\n"
"  document.getElementById('running-progress').innerText='0/'+tout+'s';\n"
"  if(timer) clearInterval(timer);\n"
"  timer=setInterval(function(){\n"
"    elapsed++;\n"
"    document.getElementById('running-progress').innerText=elapsed+'/'+tout+'s';\n"
"    if(elapsed>=tout) clearInterval(timer);\n"
"  },1000);\n"
"  setTimeout(getStatus,1500);\n"
"}\n"

"function showResult(status,type,sz,cnt){\n"
"  clearInterval(timer);\n"
"  var types=['Passive','Handshake','PMKID','DoS','Beacon Spam','Mass Deauth'];\n"
"  document.getElementById('result-meta').innerText='Status: '+status+' | Type: '+(types[type]||'Unknown');\n"
"  var el=document.getElementById('result-content');\n"
"  el.innerHTML='';\n"
"  if(type===0) el.innerHTML='<p>Captured! <a class=\"dl-btn\" href=\"capture.pcap\">Download PCAP</a></p>';\n"
"  else if(type===1) el.innerHTML='<p>Captured! <a class=\"dl-btn\" href=\"capture.hccapx\">Download HCCAPX</a> <a class=\"dl-btn\" href=\"capture.pcap\">Download PCAP</a></p>';\n"
"  else if(type===2) renderPmkid(cnt,sz,el);\n"
"  else el.innerHTML='<p>Done.</p>';\n"
"  show('result');\n"
"}\n"

"function renderPmkid(d,sz,el){\n"
"  var ap='',sta='',ssid='',ssid_h='',pmkid='';\n"
"  for(var i=0;i<6;i++) ap+=d[i].toString(16).padStart(2,'0');\n"
"  for(var i=0;i<6;i++) sta+=d[i+6].toString(16).padStart(2,'0');\n"
"  var slen=d[12];\n"
"  for(var i=0;i<slen;i++){ssid+=String.fromCharCode(d[13+i]);ssid_h+=d[13+i].toString(16).padStart(2,'0');}\n"
"  var idx=13+slen;\n"
"  for(var i=0;i<sz-idx;i++) pmkid+=d[idx+i].toString(16).padStart(2,'0');\n"
"  el.innerHTML='<pre>AP:  '+ap+'\\nSTA: '+sta+'\\nSSID: '+ssid+'\\nPMKID: '+pmkid+'</pre>';\n"
"  el.innerHTML+='<p style=\"margin-top:8px;font-size:12px\">Hashcat 22000:</p><pre>WPA*01*'+pmkid+'*'+ap+'*'+sta+'*'+ssid_h+'***</pre>';\n"
"}\n"

"function updateFields(el){\n"
"  var v=parseInt(el.value);\n"
"  var mg=document.getElementById('method_grp');\n"
"  var ms=document.getElementById('attack_method');\n"
"  var to=document.getElementById('attack_timeout');\n"
"  ms.innerHTML=''; mg.style.display='none';\n"
"  if(v===1){to.value=60;mg.style.display='block';['Rogue AP','Broadcast Deauth','Passive Only'].forEach(function(t,i){ms.add(new Option(t,i));});}\n"
"  else if(v===3){to.value=120;mg.style.display='block';['Rogue AP','Broadcast Deauth','Combined'].forEach(function(t,i){ms.add(new Option(t,i));});}\n"
"  else if(v===4){to.value=120;mg.style.display='none';}\n"
"  else if(v===5){to.value=60;mg.style.display='none';}\n"
"  else{to.value=30;}\n"
"}\n"

"function resetAttack(){\n"
"  fetch('reset',{method:'HEAD'}).then(function(){selId=-1;document.getElementById('target_ssid').value='';getStatus();});\n"
"}\n"

"function hideAll(){document.querySelectorAll('section').forEach(function(s){s.classList.remove('vis');});}\n"
"function show(id){document.getElementById(id).classList.add('vis');}\n"
"function showErr(m){var e=document.getElementById('errors');e.innerText=m;e.style.display='block';}\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
#endif
